name: build-templates

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_PAT_USERNAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Build & Push Templates
        run: bash ./tools/docker-build.sh